### ISSUE TITLE
AttributeError: 'Batch' object has no attribute '_bi_layer_idx0'

### ISSUE THREAD

**Issue by chontipan** [anonyma2020/DAGNN#1]
Hi authors. Could you please suggest to solve this issue?

![image](https://user-images.githubusercontent.com/9138402/110595897-95609600-81b9-11eb-9fb2-e1e7af9694fd.png)

**Comment by vthost** [comment]
Hi! 
Did you find the issue?
If you use the OGB code from the ogb directory in the project, this attribute should be added during data pre-processing. This is the change we made to the OGB code: https://github.com/vthost/DAGNN/blob/c935561710da94a6131342d4292bf9ee9da38883/ogb/io/read_graph_pyg.py#L51

**Comment by chontipan** [comment]
Thank you very much. It is solved!
