### ISSUE TITLE
Any idea to make DAGNN iterative?

### ISSUE THREAD

**Issue by lee-man** [anonyma2020/DAGNN#2]
Hi @vthost ,

Thanks for your excellent work. I reused your code to re-implement the model structure stated in the Circuit-Sat paper (https://openreview.net/forum?id=BJxgz2R9t7). In their paper, the model structure is named DGRNN, and the major difference between it and your work is that they use an iterative propagation scheme with a recurrent neural network to update the hidden state of each node. Basically, they will run tens of iteration to make the hidden state of nodes be converged.

I tried to re-implement their structure based on your work, but some gradient problems occurred, since we use indexing operations to slice the hidden state. Do you have any idea to make your code iterative?

Also, I wonder whether it will bring some benefits to induce recurrence (iterative) mechanisms in your work? 

Thanks,
Min

**Comment by vthost** [comment]
Hi, thanks, this is an interesting paper (not sure how it could slip my related work search)! 
I will check and get back to you later!

**Comment by vthost** [comment]
To clarify, by "iterative propagation scheme" you mean you want to introduce the T-times looping from Eq. (3)?

**Comment by lee-man** [comment]
> To clarify, by "iterative propagation scheme" you mean you want to introduce the T-times looping from Eq. (3)?

Sorry for the ambiguity. That's exactly what I mean.

**Comment by lee-man** [comment]
@vthost Sorry to bother you again. Is there any update here? Thanks!

**Comment by lee-man** [comment]
@vthost Hi, I implemented the recursive version but the experiments haven't been done yet. I will open another issue if any further discussion is needed. Thanks a lot!

**Comment by vthost** [comment]
Oh, very cool that it worked!
Sorry for not being super helpful!
