### ISSUE TITLE
Using DAGNNs for node classification?

### ISSUE THREAD

**Issue by chouhanaryan** [anonyma2020/DAGNN#3]
Hi, this is great work! Sorry if this is a stupid question - but would it be possible to use this model for node classification? I have a graph dataset that is a DAG and I am trying to predict node properties and hence, your model seems like a great way to approach the problem. I'm not asking for help with any of the coding, it's just the possibility of using DAGNNs for the task that I am curious about. Thank you!

**Comment by vthost** [comment]
Hi! You can of course do the prediction on all nodes. In this case, `out` would not contains not just contain the target nodes but all.
