### ISSUE TITLE
No module named 'src'

### ISSUE THREAD

**Issue by MatPerr** [anonyma2020/DAGNN#4]
Hi and thank you for your great work ! I have a problem running the code with Windows 10 and git bash though, when I do : 

./scripts/na_train.sh 0 DAGNN

In the DAGNN repository, I get the following error : 

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from util import *
  File "C:\Users\mat\Documents\Thèse\graphemb\DAGNN\dvae\util.py", line 20, in <module>
    from src.utils_dag import add_order_info
ModuleNotFoundError: No module named 'src'

Maybe I am doing something wrong but I can't figure out what

**Comment by marvher** [comment]
I solved a similiar error by adding the src folder to the sys path, like:

```
import sys
sys.path.append('/path_to_repo/DAGNN/src')
from utils_dag import add_order_info
```
