### ISSUE TITLE
Topological batching

### ISSUE THREAD

**Issue by choltz95** [anonyma2020/DAGNN#5]
Hi- great paper! Thank you for making your code open source. Was wondering if this implementation includes routines for topological batching or if this was something that was explored in the paper in a more abstract sense.

**Comment by vthost** [comment]
Hi, 
The batches are pre-computed [here](https://github.com/vthost/DAGNN/blob/3191b2cc4f923d523ece3962c96a0e3dd54f1a0b/src/utils_dag.py#L8) and we then do regular batching just based on the pre-computed indices.
Sorry for the late reply, I somehow missed this issue...
