### ISSUE TITLE
DAGNN forward - 'GlobalStorage' object has no attribute '_bi_layer_idx0' (AttributeError)

### ISSUE THREAD

**Issue by marvher** [anonyma2020/DAGNN#6]
Thanks @vthost  for sharing your code.

I have almost got your code running.. However, now I got an error in the forward of the DAGNN at line 134:
`        G.bi_layer_index = torch.stack([
            torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0),
            torch.stack([G._bi_layer_idx1, G._bi_layer_index1], dim=0)
        ], dim=0)`

It seems that **_bi_layer_idx0** can not be found.. In generell why did you create an index mapping here?
And what is the difference between **_bi_layer_idx0** and **_bi_layer_index0**?

I would really appreciate your help here, thanks!

**_______________________________________________ ERROR Message _____________________________________________________**

0.911261856688407
Let's use 0 GPUs! -- DataParallel running also on CPU only
=====Fold 1, Epoch 1
Iteration:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s] Traceback (most recent call last):
  File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 50, in __getattr__
    return self[key]
  File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 70, in __getitem__
    return self._mapping[key]
KeyError: '_bi_layer_idx0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_pyg.py", line 409, in <module>
    main()
  File "main_pyg.py", line 318, in main
    loss, train_perf = train(model, device, train_loader, optimizer, args, evaluator, arr_to_seq = lambda arr: decode_arr_to_seq(arr, idx2vocab))
  File "main_pyg.py", line 52, in train
    pred_list = model(batch)
  File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\masterarbeit\code\DAGNN\ogbg-code\tg\data_parallel.py", line 50, in forward
    return self.module(data)
  File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\masterarbeit\code\DAGNN\ogbg-code\model\dagnn.py", line 135, in forward
    torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0),
  File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\data.py", line 362, in __getattr__
    return getattr(self._store, key)
  File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 52, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute '_bi_layer_idx0'

**Comment by vthost** [comment]
Hi @marvher 
Did you try the solution mentioned in #1 ?

**Comment by LUOyk1999** [comment]
Thanks @vthost.
Solution mentioned in https://github.com/vthost/DAGNN/issues/1 cannot solve the problem.
![image](https://user-images.githubusercontent.com/57895481/187384212-7abb8705-b39d-4c2e-9e14-f03bcef5f814.png)

torch==1.12.1+cu116, torch-geometric==2.0.4

**Comment by vthost** [comment]
We assume by now that torch geometric has changed a critical setting in the dataset classes. It would be safest to either use the version recommended in the README or check which parts changed in torch geometric and try to solve it on that end. Please let us know in case you get it to run!

**Comment by LUOyk1999** [comment]
Okay, thank you. We're recently doing GNN model research on DAG and studying your paper :).

**Comment by LUOyk1999** [comment]
Hi, @vthost.
After many attempts, I modified the code in three places and then get it to run.
I think I may have solved the problem.
My environment is torch==1.12.1+cu116, torch-geometric==2.0.4.
![image](https://user-images.githubusercontent.com/57895481/187588343-b2229849-e333-4b91-a081-e72a4d4f025a.png)
![image](https://user-images.githubusercontent.com/57895481/187588368-d00b55a1-5205-4891-8742-9be6a5d41bbc.png)
![image](https://user-images.githubusercontent.com/57895481/187588388-dcd83b35-f09f-4309-b006-157f68628978.png)
![image](https://user-images.githubusercontent.com/57895481/187589924-bb40e202-8441-4f94-8626-0f8b49b3450a.png)

**Comment by vthost** [comment]
Thank you for letting us know, this might be interesting for @marvher as well!

**Comment by ZhongLIFR** [comment]
> Hi, @vthost. After many attempts, I modified the code in three places and then get it to run. I think I may have solved the problem. My environment is torch==1.12.1+cu116, torch-geometric==2.0.4. ![image](https://user-images.githubusercontent.com/57895481/187588343-b2229849-e333-4b91-a081-e72a4d4f025a.png) ![image](https://user-images.githubusercontent.com/57895481/187588368-d00b55a1-5205-4891-8742-9be6a5d41bbc.png) ![image](https://user-images.githubusercontent.com/57895481/187588388-dcd83b35-f09f-4309-b006-157f68628978.png) ![image](https://user-images.githubusercontent.com/57895481/187589924-bb40e202-8441-4f94-8626-0f8b49b3450a.png)

Hi, I had the same errors and tried your solutions. BUT it did not work, and I got another error as follows:
____________________________________________________________
AttributeError: 'GlobalStorage' object has no attribute 'bi_layer_idx0'
____________________________________________________________

**Comment by ZhongLIFR** [comment]
> Thanks @vthost for sharing your code.
> 
> I have almost got your code running.. However, now I got an error in the forward of the DAGNN at line 134: ` G.bi_layer_index = torch.stack([ torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0), torch.stack([G._bi_layer_idx1, G._bi_layer_index1], dim=0) ], dim=0)`
> 
> It seems that **_bi_layer_idx0** can not be found.. In generell why did you create an index mapping here? And what is the difference between **_bi_layer_idx0** and **_bi_layer_index0**?
> 
> I would really appreciate your help here, thanks!
> 
> **_______________________________________________ ERROR Message _____________________________________________________**
> 
> 0.911261856688407 Let's use 0 GPUs! -- DataParallel running also on CPU only =====Fold 1, Epoch 1 Iteration: 0%| | 0/1 [00:00<?, ?it/s] Traceback (most recent call last): File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 50, in **getattr** return self[key] File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 70, in **getitem** return self._mapping[key] KeyError: '_bi_layer_idx0'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main_pyg.py", line 409, in main() File "main_pyg.py", line 318, in main loss, train_perf = train(model, device, train_loader, optimizer, args, evaluator, arr_to_seq = lambda arr: decode_arr_to_seq(arr, idx2vocab)) File "main_pyg.py", line 52, in train pred_list = model(batch) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\masterarbeit\code\DAGNN\ogbg-code\tg\data_parallel.py", line 50, in forward return self.module(data) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\masterarbeit\code\DAGNN\ogbg-code\model\dagnn.py", line 135, in forward torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0), File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\data.py", line 362, in **getattr** return getattr(self._store, key) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 52, in **getattr** raise AttributeError( AttributeError: 'GlobalStorage' object has no attribute '_bi_layer_idx0'

G is a "GlobalStorage" object here. I checked all the available attributes for this type of object in torch 1.13.1, and they have the following attributes (apparently "_bi_layer_idx0" cannot be found ):

['__call__', '__cat_dim__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__inc__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_all_edges_to_layout', '_edge_attr_cls', '_edge_to_layout', '_get_edge_index', '_get_tensor', '_get_tensor_size', '_multi_get_tensor', '_put_edge_index', '_put_tensor', '_remove_tensor', '_store', '_tensor_attr_cls', '_to_type', 'apply', 'apply_', 'batch', 'clone', 'coalesce', 'contains_isolated_nodes', 'contains_self_loops', 'contiguous', 'coo', 'cpu', 'csc', 'csr', 'cuda', 'debug', 'detach', 'detach_', 'edge_attr', 'edge_index', 'edge_stores', 'edge_weight', 'from_data_list', 'from_dict', 'get_all_edge_attrs', 'get_all_tensor_attrs', 'get_edge_index', 'get_example', 'get_tensor', 'get_tensor_size', 'has_isolated_nodes', 'has_self_loops', 'index_select', 'is_coalesced', 'is_cuda', 'is_directed', 'is_edge_attr', 'is_node_attr', 'is_undirected', 'items', 'keys', 'multi_get_tensor', 'node_stores', 'num_edge_features', 'num_edges', 'num_faces', 'num_features', 'num_graphs', 'num_node_features', 'num_nodes', 'pin_memory', 'pos', 'put_edge_index', 'put_tensor', 'record_stream', 'remove_tensor', 'requires_grad_', 'share_memory_', 'size', 'stores', 'stores_as', 'subgraph', 'to', 'to_data_list', 'to_dict', 'to_heterogeneous', 'to_namedtuple', 'update_tensor', 'validate', 'view', 'x', 'y']

**Comment by Eilowangfang** [comment]
> > Thanks @vthost for sharing your code.
> > I have almost got your code running.. However, now I got an error in the forward of the DAGNN at line 134: ` G.bi_layer_index = torch.stack([ torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0), torch.stack([G._bi_layer_idx1, G._bi_layer_index1], dim=0) ], dim=0)`
> > It seems that **_bi_layer_idx0** can not be found.. In generell why did you create an index mapping here? And what is the difference between **_bi_layer_idx0** and **_bi_layer_index0**?
> > I would really appreciate your help here, thanks!
> > **_______________________________________________ ERROR Message _____________________________________________________**
> > 0.911261856688407 Let's use 0 GPUs! -- DataParallel running also on CPU only =====Fold 1, Epoch 1 Iteration: 0%| | 0/1 [00:00<?, ?it/s] Traceback (most recent call last): File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 50, in **getattr** return self[key] File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 70, in **getitem** return self._mapping[key] KeyError: '_bi_layer_idx0'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "main_pyg.py", line 409, in main() File "main_pyg.py", line 318, in main loss, train_perf = train(model, device, train_loader, optimizer, args, evaluator, arr_to_seq = lambda arr: decode_arr_to_seq(arr, idx2vocab)) File "main_pyg.py", line 52, in train pred_list = model(batch) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\masterarbeit\code\DAGNN\ogbg-code\tg\data_parallel.py", line 50, in forward return self.module(data) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\masterarbeit\code\DAGNN\ogbg-code\model\dagnn.py", line 135, in forward torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0), File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\data.py", line 362, in **getattr** return getattr(self._store, key) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 52, in **getattr** raise AttributeError( AttributeError: 'GlobalStorage' object has no attribute '_bi_layer_idx0'
> 
> G is a "GlobalStorage" object here. I checked all the available attributes for this type of object in torch 1.13.1, and they have the following attributes (apparently "_bi_layer_idx0" cannot be found ):
> 
> ['**call**', '**cat_dim**', '**class**', '**contains**', '**copy**', '**deepcopy**', '**delattr**', '**delitem**', '**dict**', '**dir**', '**doc**', '**eq**', '**format**', '**ge**', '**getattr**', '**getattribute**', '**getitem**', '**getstate**', '**gt**', '**hash**', '**inc**', '**init**', '**init_subclass**', '**iter**', '**le**', '**len**', '**lt**', '**module**', '**ne**', '**new**', '**reduce**', '**reduce_ex**', '**repr**', '**setattr**', '**setitem**', '**setstate**', '**sizeof**', '**str**', '**subclasshook**', '**weakref**', '_all_edges_to_layout', '_edge_attr_cls', '_edge_to_layout', '_get_edge_index', '_get_tensor', '_get_tensor_size', '_multi_get_tensor', '_put_edge_index', '_put_tensor', '_remove_tensor', '_store', '_tensor_attr_cls', '_to_type', 'apply', 'apply_', 'batch', 'clone', 'coalesce', 'contains_isolated_nodes', 'contains_self_loops', 'contiguous', 'coo', 'cpu', 'csc', 'csr', 'cuda', 'debug', 'detach', 'detach_', 'edge_attr', 'edge_index', 'edge_stores', 'edge_weight', 'from_data_list', 'from_dict', 'get_all_edge_attrs', 'get_all_tensor_attrs', 'get_edge_index', 'get_example', 'get_tensor', 'get_tensor_size', 'has_isolated_nodes', 'has_self_loops', 'index_select', 'is_coalesced', 'is_cuda', 'is_directed', 'is_edge_attr', 'is_node_attr', 'is_undirected', 'items', 'keys', 'multi_get_tensor', 'node_stores', 'num_edge_features', 'num_edges', 'num_faces', 'num_features', 'num_graphs', 'num_node_features', 'num_nodes', 'pin_memory', 'pos', 'put_edge_index', 'put_tensor', 'record_stream', 'remove_tensor', 'requires_grad_', 'share_memory_', 'size', 'stores', 'stores_as', 'subgraph', 'to', 'to_data_list', 'to_dict', 'to_heterogeneous', 'to_namedtuple', 'update_tensor', 'validate', 'view', 'x', 'y']

May I know if you solved this issue? I kind got same trouble.

**Comment by Eilowangfang** [comment]
> > > Thanks @vthost for sharing your code.
> > > I have almost got your code running.. However, now I got an error in the forward of the DAGNN at line 134: ` G.bi_layer_index = torch.stack([ torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0), torch.stack([G._bi_layer_idx1, G._bi_layer_index1], dim=0) ], dim=0)`
> > > It seems that **_bi_layer_idx0** can not be found.. In generell why did you create an index mapping here? And what is the difference between **_bi_layer_idx0** and **_bi_layer_index0**?
> > > I would really appreciate your help here, thanks!
> > > **_______________________________________________ ERROR Message _____________________________________________________**
> > > 0.911261856688407 Let's use 0 GPUs! -- DataParallel running also on CPU only =====Fold 1, Epoch 1 Iteration: 0%| | 0/1 [00:00<?, ?it/s] Traceback (most recent call last): File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 50, in **getattr** return self[key] File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 70, in **getitem** return self._mapping[key] KeyError: '_bi_layer_idx0'
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last): File "main_pyg.py", line 409, in main() File "main_pyg.py", line 318, in main loss, train_perf = train(model, device, train_loader, optimizer, args, evaluator, arr_to_seq = lambda arr: decode_arr_to_seq(arr, idx2vocab)) File "main_pyg.py", line 52, in train pred_list = model(batch) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\masterarbeit\code\DAGNN\ogbg-code\tg\data_parallel.py", line 50, in forward return self.module(data) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\masterarbeit\code\DAGNN\ogbg-code\model\dagnn.py", line 135, in forward torch.stack([G._bi_layer_idx0, G._bi_layer_index0], dim=0), File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\data.py", line 362, in **getattr** return getattr(self._store, key) File "D:\masterarbeit\code\DAGNN\venv_dagnn\lib\site-packages\torch_geometric\data\storage.py", line 52, in **getattr** raise AttributeError( AttributeError: 'GlobalStorage' object has no attribute '_bi_layer_idx0'
> > 
> > 
> > G is a "GlobalStorage" object here. I checked all the available attributes for this type of object in torch 1.13.1, and they have the following attributes (apparently "_bi_layer_idx0" cannot be found ):
> > ['**call**', '**cat_dim**', '**class**', '**contains**', '**copy**', '**deepcopy**', '**delattr**', '**delitem**', '**dict**', '**dir**', '**doc**', '**eq**', '**format**', '**ge**', '**getattr**', '**getattribute**', '**getitem**', '**getstate**', '**gt**', '**hash**', '**inc**', '**init**', '**init_subclass**', '**iter**', '**le**', '**len**', '**lt**', '**module**', '**ne**', '**new**', '**reduce**', '**reduce_ex**', '**repr**', '**setattr**', '**setitem**', '**setstate**', '**sizeof**', '**str**', '**subclasshook**', '**weakref**', '_all_edges_to_layout', '_edge_attr_cls', '_edge_to_layout', '_get_edge_index', '_get_tensor', '_get_tensor_size', '_multi_get_tensor', '_put_edge_index', '_put_tensor', '_remove_tensor', '_store', '_tensor_attr_cls', '_to_type', 'apply', 'apply_', 'batch', 'clone', 'coalesce', 'contains_isolated_nodes', 'contains_self_loops', 'contiguous', 'coo', 'cpu', 'csc', 'csr', 'cuda', 'debug', 'detach', 'detach_', 'edge_attr', 'edge_index', 'edge_stores', 'edge_weight', 'from_data_list', 'from_dict', 'get_all_edge_attrs', 'get_all_tensor_attrs', 'get_edge_index', 'get_example', 'get_tensor', 'get_tensor_size', 'has_isolated_nodes', 'has_self_loops', 'index_select', 'is_coalesced', 'is_cuda', 'is_directed', 'is_edge_attr', 'is_node_attr', 'is_undirected', 'items', 'keys', 'multi_get_tensor', 'node_stores', 'num_edge_features', 'num_edges', 'num_faces', 'num_features', 'num_graphs', 'num_node_features', 'num_nodes', 'pin_memory', 'pos', 'put_edge_index', 'put_tensor', 'record_stream', 'remove_tensor', 'requires_grad_', 'share_memory_', 'size', 'stores', 'stores_as', 'subgraph', 'to', 'to_data_list', 'to_dict', 'to_heterogeneous', 'to_namedtuple', 'update_tensor', 'validate', 'view', 'x', 'y']
> 
> May I know if you solved this issue? I kind got same trouble.

Zhong, appreciate your help. 
Anybody has the same issue, please refer to issues 10.
