### ISSUE TITLE
sh ./scripts/ogb_tok.sh

### ISSUE THREAD

**Issue by UltramanSleepless** [anonyma2020/DAGNN#9]
when i run the code sh ./scripts/ogb_tok.sh, it cost a long time. And, it stops at the moment "started experiments".

**Comment by vthost** [comment]
The first time it will download and preprocess the data, this may take some time. Could you please double check if you used the package versions we recommend?

**Comment by vthost** [comment]
Closing this for now. Feel free to add comments/questions if needed!
